version: '3.9'

services:
  devcontainer:
    build:  
      dockerfile: Dockerfile
      args:
        VARIANT: 18-bullseye
        TERRAFORM_VERSION: 1.0.11
      context: .
    environment:
      - PLATFORM=Local
      - CLOUD_ENDPOINT_OVERRIDE=http://localhost:4566
      - AWS_REGION=us-east-1
    ports:
      - 3000:3000
      - 9229:9229
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached